services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/dockerfile
  #   image: mostafah01/tasks-managment-app
  #   ports:
  #     - 3030:3030
  #   env_file:
  #     - ../.env
  #   depends_on:
  #     - mongodb
  #     - redis
  #     - selenium-hub
  #   # volumes:



  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017' # Map container port to host port

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  selenium-hub:
    image: selenium/standalone-chrome
    ports:
      - '4444:4444'
      - '7900:7900'
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2g
    restart: always
    

volumes:
  mongo_data:
