services:
  # app:
  #   build:
  #     target: development
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - 3030:3030
  #   # volumes:
  #   # - ../dist/:/app/dist:ro



  mongodb:
    ports:
      - '27017:27017' # Map container port to host port


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb

  redis:
    ports:
      - '6379:6379' # Map container port to host port

  selenium-hub:
    ports:
      - '4444:4444'
      - '7900:7900'
