services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/dockerfile
  #   image: mostafah01/tasks-managment-app:fix-dockerfile
  #   env_file:
  #     - ../.env
  #   depends_on:
  #     - mongodb
  #     - redis
  #     - selenium-hub
  #   # volumes:



  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db


  redis:
    image: redis
    restart: always

  selenium-hub:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 2g
    restart: always
    

volumes:
  mongo_data:
