# Base image
FROM node:18  as base

WORKDIR /app
COPY ../package.json .
EXPOSE 3030


FROM base as development
# RUN npm install
COPY ../. .
RUN npm run build
# COPY dist /dist/
# CMD ["npm", "run", "docker:dev"]
CMD ["node", "./dist/src/main.js", "--watch"]


FROM base as production
RUN npm install --omit=dev
CMD ["npm", "run", "start:prod"]
