# Base image
FROM node:18  as base

WORKDIR /app
COPY ../package.json .
EXPOSE 3030
COPY ../. .
RUN npm run build


FROM base as development
RUN npm install
# COPY dist /dist/
# CMD ["node", "./dist/src/main.js", "--watch"]


FROM base as production
RUN npm install --omit=dev
CMD ["npm", "run", "prod"]
# CMD ["npm", "run", "start:prod"]
